# Generated by Django 5.2.4 on 2025-09-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada_x', models.IntegerField()),
                ('coordenada_y', models.IntegerField()),
            ],
            options={
                'unique_together': {('coordenada_x', 'coordenada_y')},
            },
        ),
        migrations.CreateModel(
            name='Iteracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_errores', models.IntegerField(default=0)),
                ('grafica_image', models.ImageField(blank=True, null=True, upload_to='graficas/')),
                ('puntos', models.ManyToManyField(related_name='iteraciones', to='DataVisualization.punto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
