# Generated by Django 5.2.4 on 2025-09-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.IntegerField(help_text='Coordenada X del punto.')),
                ('y_value', models.IntegerField(help_text='Coordenada Y del punto.')),
            ],
            options={
                'verbose_name': 'Punto de Dato',
                'verbose_name_plural': 'Puntos de Datos',
            },
        ),
        migrations.CreateModel(
            name='IterationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la iteración.')),
            ],
            options={
                'verbose_name': 'Corrida de Iteración',
                'verbose_name_plural': 'Corridas de Iteraciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='PlotResult',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='iteration_run',
            field=models.ForeignKey(help_text='La corrida de iteración a la que pertenece este punto.', on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='DataVisualization.iterationrun'),
        ),
    ]
